[settings]
minimum_release_age = "2d"

[tools]
go = "1.27"
node = "24"
python = "3.13"

age = "latest"
ast-grep = "latest"
bun = "latest"
fnox = "latest"
pnpm = "11"
uv = "latest"
vault = "latest"

"npm:markdownlint-cli" = "latest"
"npm:yaml-language-server" = "latest"
"npm:@nanonets/graft" = { version = "latest", allow_builds = ["tree-sitter-kotlin"] }

[tasks.go-tools]
run = """
go install golang.org/x/tools/gopls@latest
go install honnef.co/go/tools/cmd/staticcheck@latest
"""
