[settings]
minimum_release_age = "2d"

[tools]
node = "24"
python = "3.13"
go = "1.27"
pnpm = "11"
uv = "latest"
bun = "latest"
age = "latest"
fnox = "latest"
vault = "latest"
"npm:markdownlint-cli" = "latest"
"npm:yaml-language-server" = "latest"

[tasks.go-tools]
run = """
go install golang.org/x/tools/gopls@latest
go install honnef.co/go/tools/cmd/staticcheck@latest
"""
