tap "homebrew/bundle"
tap "homebrew/cask"
tap "wallix/awless"

# cask "atom"
# cask "box-sync"
# cask "burp-suite"
# cask "corretto"
# cask "docker"
# cask "firefox"
# cask "google-chrome"
# cask "iterm2"
# cask "macvim"
# cask "owasp-zap"
# cask "postman"
# cask "pycharm-ce"
# cask "wireshark"

brew "adns"
brew "ansible"
brew "ansible-lint"
brew "awscli"
brew "awless"
brew "binwalk"
brew "cfn-lint"
brew "cmake"
brew "coreutils"
brew "csshx"
brew "docker-machine"
brew "gcc"
brew "gdbm"
brew "gettext"
brew "git"
brew "git-crypt"
brew "git-flow"
brew "gnu-sed"
brew "gnupg"
brew "gnutls"
brew "go"
brew "gradle"
brew "grep"
brew "groovy"
brew "httping"
brew "ipcalc"
brew "ispell"
brew "jq"
brew "jsonlint"
brew "jython"
brew "kubectl"
brew "kops"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "llvm"
brew "mas"
brew "maven"
brew "minikube"
brew "nmap"
brew "node"
brew "openssl"
brew "packer"
brew "pcre"
brew "pcre2"
brew "python"
brew "ruby"
brew "shellcheck"
brew "siege"
brew "sqlite"
brew "terraform"
brew "testssl"
brew "the_silver_searcher"
brew "tmux"
brew "tmuxinator-completion"
brew "vim"
brew "wget"

mas "Divvy", id: 413857545
mas "Microsoft Remote Desktop 10", id: 1295203466
mas "Slack", id: 803453959
